Fix cpio encoding of empty files when creating an RPM.
Previously the link count in the cpio file header was incorrectly set
to 2 for empty files.  This occasionally caused an error such as the
following when attemptint to install the RPM.

error: unpacking of archive failed on file /PATH_TO_FILE/include/.ignore;5a2ed95c: cpio: Missing hard link(s)